# Generated by Django 4.2.6 on 2025-08-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('transporter', 'Transporter'), ('admin', 'Admin')], default='farmer', max_length=20),
        ),
    ]
