# Generated by Django 4.2.6 on 2025-09-01 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wheat', 'Wheat'), ('rice', 'Rice'), ('maize', 'Maize'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('other', 'Other')], max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity in kg or units')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit in ₹', max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
