# Generated by Django 4.2.6 on 2025-09-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='price_per_unit',
        ),
        migrations.AddField(
            model_name='crop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
