# Generated by Django 4.2.6 on 2025-09-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_transporterprofile_orderitem'),
    ]

    operations = [
        
    ]
