# Generated by Django 4.2.6 on 2025-09-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_transporterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='assigned', max_length=30),
        ),
    ]
